import type { Metadata } from 'next'
import { Inter } from 'next/font/google'
import Footer from '../components/common/footer/Footer'
import Header from '../components/common/header/Header'
import './globals.css'

const inter = Inter({ subsets: ['latin'] })

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode
}>) {
  return (
    <html lang='en'>
      <body className={inter.className}>
        <Header />
        <main className='flex min-h-screen flex-col items-center justify-between'>{children}</main>
        <Footer />
      </body>
    </html>
  )
}
